# =============================================================
#  US Close deploy (부 PC, runs Saturday early morning KST)
#
#  Triggered ~30 min after US Friday session ends:
#    - Standard time (Nov-Mar): US close 06:00 KST -> run 06:30 KST
#    - DST            (Mar-Nov): US close 05:00 KST -> run 06:30 KST
#  Single 06:30 KST trigger covers both (always post-close).
#
#  Captures fresh US Friday close for:
#    - 미 증시 (DOW, SPX, NASDAQ, GICS sectors)        via Yahoo history
#    - 미국 금리 (US2Y, US10Y, US30Y)                   via Investing + Yahoo
#    - 환율 (DXY plus revalidation of cross rates)      via Yahoo + Naver
#    - FedWatch (post-week US futures settle)            via Investing
#    - Calendar / market-update-frozen                   via Investing
#
#  Then commits + pushes ONLY data files (no code). Other-PC RepoSync
#  picks it up within 5 min.
#
#  IMPORTANT: do NOT also register DailyDeploy/FridayDeploy on 부 PC —
#  they would conflict with 주 PC's pushes.
# =============================================================
$ErrorActionPreference = 'Continue'
$root = $PSScriptRoot
Set-Location $root

Write-Host ""
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host " US Close deploy - $($(Get-Date).ToString('yyyy-MM-dd HH:mm'))" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

# 0. Sync from origin first (so we don't clobber peer/IPO from 주 PC's Friday deploy)
Write-Host "[0/5] Sync from origin/main..." -ForegroundColor Yellow
& git -C $root pull --rebase --autostash 2>&1 | Out-Null

# 1. Market data (US indices, US rates, sectors, commodities, FX)
Write-Host "[1/5] Refresh market data (US close basis)..." -ForegroundColor Yellow
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'refresh.ps1')

# 2. Calendar
Write-Host "[2/5] Refresh calendar..." -ForegroundColor Yellow
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'fetch-calendar.ps1')

# 3. FedWatch (CME Fed Funds Futures — post-week settle)
Write-Host "[3/5] Refresh FedWatch..." -ForegroundColor Yellow
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'fetch-fedwatch.ps1')

# 4. Naver FX (revalidate Seoul-close — main pair stable since Friday 15:30 KST)
Write-Host "[4/5] Refresh Naver FX..." -ForegroundColor Yellow
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'fetch-naver-fx.ps1')

# 5. Commit + push (only data files; never code)
Write-Host "[5/5] Commit + push..." -ForegroundColor Yellow
$gitStatus = git status --porcelain 2>&1
if ([string]::IsNullOrWhiteSpace($gitStatus)) {
    Write-Host "  No changes -- nothing to commit." -ForegroundColor DarkGray
} else {
    $forceFiles = @(
        'data.json',
        'calendar.json',
        'calendar-week.json',
        'calendar-next-week.json',
        'market-update-frozen.json',
        'fedwatch.json',
        'fx-naver-snapshot.json',
        'capmkt-freeze.json',
        'user-state.json'
    )
    git add -f $forceFiles 2>&1 | Out-Null
    # Add any other newly-untracked data files (.md generated by claude tasks etc.)
    git add -A 2>&1 | Out-Null

    Write-Host "  Staged:" -ForegroundColor DarkGray
    git status --short | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }

    $ts = (Get-Date).ToString('yyyy-MM-dd HH:mm')
    git commit -m "US-close deploy $ts (부 PC)" 2>&1 | Out-Null

    # Re-pull once more in case origin moved during commit, then push
    git pull --rebase --autostash 2>&1 | Out-Null
    git push 2>&1 | Tee-Object -Variable pushOut | Out-Null
    $pushOut | ForEach-Object { Write-Host "    $_" -ForegroundColor Green }
}

Write-Host ""
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host " Done. Cloudflare auto-deploys in 1-2 min." -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Cyan
